### ISSUE TITLE
breakseq2 -2.2- has requirement pysam==0.7.7, but you'll have pysam 0.15.1 which is incompatible

### ISSUE THREAD

**Issue by mattdmem** [dnanexus/parliament2#21]
I get the following problem when I try to run parliament2

breakseq2 -2.2- has requirement pysam==0.7.7, but you'll have pysam 0.15.1 which is incompatible

command: 

docker run -v <INPUT_DIR>:/home/dnanexus/in -v <OUTUT_DIR>:/home/dnanexus/out dnanexus/parliament2:0.1.8 --bam .sorted.markdup.bam --bai .sorted.markdup.bam.bai -r --breakdancer --cnvnator --manta --genotype

**Comment by seandavi** [comment]
Any thought of using conda environments to isolate the various requirements and executables? Under docker, it isn't a big deal, but under singularity (useful in an HPC environment), installing using sudo/root is problematic.

**Comment by slzarate** [comment]
Thanks, I'll look into this in the near future.
