### ISSUE TITLE
I tried with parliament2.py

### ISSUE THREAD

**Issue by pinninti19** [dnanexus/parliament2#23]
I tried to run manually, it pops a error problem with the input I changed my input showing the same error ?

 ./parliament2.py --bam /data/SRR.gsnap.sort.bam --bai /data/SRR2052405.gsnap.sort.bai -r /data/Ref/hg38.fa --fai /data/Ref/hg38.fa.fai --prefix RG@SRR.gsnap.sort.bam.vcf  --breakdancer --breakseq --manta --cnvnator --lumpy --delly_deletion --delly_insertion --delly_inversion --delly_duplication --genotype

**Comment by slzarate** [comment]
Hi,

Parliament2 is meant to be run as a Docker image. Simply running the Python script will not work, as it requires dependencies not included in just the script itself. You can read the instructions for installing the Docker image [here](https://github.com/dnanexus/parliament2#installing).

Best,
Samantha

**Comment by pinninti19** [comment]
I pull the docker image not able to run parliament2. How to solve this problem ?

**sudo docker pull dnanexus/parliament2:hgsc**
[sudo] password for pinn: 
hgsc: Pulling from dnanexus/parliament2
Digest: sha256:be8e18c7f5f9b47a5b2f671fb96bfa42b6ceb95c56946739ed5ee43c0115ae76
Status: Image is up to date for dnanexus/parliament2:hgsc

**sudo docker images**
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
dnanexus/parliament2   hgsc                12ebe0729187        6 days ago          7.41GB
hello-world            latest              4ab4c602aa5e        4 weeks ago         1.84kB
 **sudo docker run parliament2 -h**
Unable to find image 'parliament2:latest' locally
docker: Error response from daemon: repository parliament2 not found: does not exist or no pull access.

**Comment by slzarate** [comment]
Thank you for pointing this out; I will update this in the documentation. You have to include the Docker image tag: `docker run parliament2:hgsc -h`.

**Comment by pinninti19** [comment]
Hey, I tried in my computer with tag (hgsc) not working ?

pinn:~$**sudo docker run parliament2:hgsc -h**
Unable to find image 'parliament2:hgsc' locally
docker: Error response from daemon: repository parliament2 not found: does not exist or no pull access.
See 'docker run --help'.
pinn:~$ **sudo docker images**
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
dnanexus/parliament2   hgsc                12ebe0729187        6 days ago          7.41GB
hello-world            latest              4ab4c602aa5e        4 weeks ago         1.84kB

**Comment by slzarate** [comment]
Sorry. The call should be `docker run dnanexus/parliament2:hgsc -h`.

**Comment by slzarate** [comment]
I am unable to replicate this issue. Are you sure the image downloaded fully? The dependencies for Parliament2 should be self-contained in the Docker image. It might be missing a layer if you're encountering this issue. You should see the message `Status: Downloaded newer image for dnanexus/parliament2:hgsc` if the `docker pull` command succeeded.

**Comment by pinninti19** [comment]
Look here, check out...
**sudo docker images**
[sudo] password for pinn: 
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
dnanexus/parliament2   hgsc                12ebe0729187        6 days ago          7.41GB
hello-world            latest              4ab4c602aa5e        4 weeks ago         1.84kB

**sudo docker run dnanexus/parliament2:hgsc -h**
Traceback (most recent call last):
File "/home/dnanexus/parliament2.py", line 3, in
import argparse
File "/miniconda/lib/python2.7/argparse.py", line 86, in
import copy as _copy
File "/miniconda/lib/python2.7/copy.py", line 52, in
import weakref
File "/miniconda/lib/python2.7/weakref.py", line 14, in
from _weakref import (
ImportError: cannot import name _remove_dead_weakref
