### ISSUE TITLE
Samtools error

### ISSUE THREAD

**Issue by abrusell** [dnanexus/parliament2#25]
Docker image installed succesfully
The tool runs but I get a samtools error:
Checking for required python modules (/usr/bin/python)...
[2018-Oct-05 14:21:37] delly -t INS -o 1.delly.insertion.vcf -g ref.fa chr.1.bam 
[2018-Oct-05 14:21:37] delly -t DEL -o 1.delly.deletion.vcf -g ref.fa chr.1.bam 
samtools view: writing to standard output failed: Broken pipe
samtools view: error closing standard output: -1

I get this error for every chromosome
It seems to be a lumpy error, I've tried to modify parliament2.sh script but I can't get rid of this

My commandline is:
docker run -v /Users/me/temp:/home/dnanexus/in -v /Users/me/temp:/home/dnanexus/out parliament2 --bam /home/dnanexus/in/subsample001.bam --bai /home/dnanexus/in/subsample001.bam.bai -r /home/dnanexus/in/Homo_sapiens_assembly38.fasta --fai /home/dnanexus/in/Homo_sapiens_assembly38.fasta.fai  --prefix subsample001 --filter_short_contigs --breakdancer --breakseq --manta --lumpy --delly_deletion --delly_insertion --svviz --svviz_only_validated_candidates

**Comment by slzarate** [comment]
Hi,

This is a known error message caused by the splitting of the BAM file. It does not seem to affect the output. You can safely ignore this.

Best,
Samantha
