### ISSUE TITLE
Not able to run Parliament2

### ISSUE THREAD

**Issue by MaestSi** [dnanexus/parliament2#27]
Dear Parliament2 developers,
I tried running the software through the docker image, but I encountered some errors:

This is the command I gave:
```
WORKING_DIR=/mnt/cifs01/simone/18PR00010
OUTPUT_DIR=$WORKING_DIR"/PARLIAMENT2_output"
BAM=alignment.rg.recalibrated.bam
BAI=alignment.rg.recalibrated.bai
REFERENCE=Homo_sapiens_assembly38.fasta.gz
FAI=Homo_sapiens_assembly38.fasta.fai
PARLIAMENT2=dnanexus/parliament2:0.1.8

docker run -v $WORKING_DIR:/home/dnanexus/in -v $OUTPUT_DIR:/home/dnanexus/out $PARLIAMENT2 --bam $BAM --bai $BAI -r $REFERENCE --fai $FAI \
> --breakdancer --breakseq --cnvnator --manta --lumpy --delly_deletion --delly_insertion --delly_inversion --delly_duplication  --genotype --svviz
```

And this was the error message: 

> gzip: /home/dnanexus/in/Homo_sapiens_assembly38.fasta already exists;   not overwritten
> Traceback (most recent call last):
>   File "/home/dnanexus/parliament2.py", line 76, in <module>
>     main()
>   File "/home/dnanexus/parliament2.py", line 70, in main
>     ref_genome_name = gunzip_input(args.ref_genome)
>   File "/home/dnanexus/parliament2.py", line 35, in gunzip_input
>     subprocess.check_call(['gunzip', input_file])
>   File "/miniconda/lib/python2.7/subprocess.py", line 190, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['gunzip', '/home/dnanexus/in/Homo_sapiens_assembly38.fasta.gz']' returned non-zero exit status 2

When tried to supply the reference file in fasta format, I had this error message instead:

> ERROR: An invalid (nonexistent) input file has been specified.
> Traceback (most recent call last):
>   File "/home/dnanexus/parliament2.py", line 76, in <module>
>     main()
>   File "/home/dnanexus/parliament2.py", line 72, in main
>     run_parliament(args.bam, args.bai, ref_genome_name, args.fai, prefix, args.filter_short_contigs, args.breakdancer, args.breakseq, args.manta, args.cnvnator, args.lumpy, args.delly_deletion, args.delly_insertion, args.delly_inversion, args.delly_duplication, args.genotype, args.svviz, args.svviz_only_validated_candidates)
>   File "/home/dnanexus/parliament2.py", line 45, in run_parliament
>     subprocess.check_call(['bash', 'parliament2.sh', bam, bai, ref_genome, fai, prefix, str(filter_short_contigs), str(breakdancer), str(breakseq), str(manta), str(cnvnator), str(lumpy), str(delly_deletion), str(delly_insertion), str(delly_inversion), str(delly_duplication), str(genotype), str(svviz), str(svviz_only_validated_candidates)])
>   File "/miniconda/lib/python2.7/subprocess.py", line 190, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['bash', 'parliament2.sh', '/home/dnanexus/in/alignment.rg.recalibrated.bam', '/home/dnanexus/in/alignment.rg.recalibrated.bai', '/home/dnanexus/in/Homo_sapiens_assembly38.fasta', '/home/dnanexus/in/Homo_sapiens_assembly38.fasta.fai', 'alignment.rg.recalibrated', 'False', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'False']' returned non-zero exit status 1

What do you think might be the issue?
Thanks

**Comment by slzarate** [comment]
Hi,

Just to clarify, when you run the second command, do you change the `REFERENCE` line to read `REFERENCE=Homo_sapiens_assembly38.fasta`?

Samantha

**Comment by MaestSi** [comment]
Yes, I did.
It is in the WORKING_DIR directory as a symbolic link.
Is it required to copy it phisically, or the link should be enough?
Thanks

**Comment by slzarate** [comment]
The code has not yet been tested using symlinks. We can add this functionality in the future, but for now, you will have to physically copy it.

**Comment by MaestSi** [comment]
Thank you very much, that was the problem preventing Parliament2 to run indeed.
Now everything works, except for the fact that svviz_outputs.tar.gz file is not generated.
Do you have any guesses about that too?

**Comment by MaestSi** [comment]
If it is a matter of days, I think I can wait for the new versione to be released; otherwise, if it is going to take some time, I would like to check that out sooner, since it would speed up manual revision very much.
Thanks

**Comment by slzarate** [comment]
OK! I am hoping to release it by the end of next week. Hopefully this is a quick enough turnaround for you.

**Comment by MaestSi** [comment]
Dear slzarate,
any update about the release date of new version?
Thanks

**Comment by slzarate** [comment]
Hi,

I am running some final tests and planning on pushing the new version later today. Thank you for your patience.

Samantha

**Comment by slzarate** [comment]
Version 0.1.9 is out now: https://github.com/dnanexus/parliament2/releases/tag/v0.1.9
