### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by karlskov** [dnanexus/parliament2#30]
When running parliament2 I get the error:
Set up and index BAM/CRAM
BAM file input, index exists
cp: error writing 'input.bam': No space left on device
cp: failed to extend 'input.bam': No space left on device
cp: error writing 'input.bam.bai': No space left on device
cp: failed to extend 'input.bam.bai': No space left on device

Any suggestions to fix this problem??

**Comment by slzarate** [comment]
Hi,

How big is the BAM file you're using and how big is the machine?

I plan on implementing a fix soon to reduce total disk usage. This may solve your problem.

Samantha

**Comment by karlskov** [comment]
Thank you Samantha!!
The machine is big but a 37G bam file was apparently too much.
Thanks for pointing out the rather obvious solution to reduce the size of the bam file.
Seems to run when working on one chromosome at a time.
Peter

**Comment by slzarate** [comment]
Thank you for reporting. We are pushing an update shortly that will improve disk space management and should hopefully avoid issues like this in the future.

**Comment by slzarate** [comment]
Version 0.1.9 is out, which hopefully helps alleviate this issue: https://github.com/dnanexus/parliament2/releases/tag/v0.1.9
