### ISSUE TITLE
Using the parliament2 container with Singularity

### ISSUE THREAD

**Issue by sgivan** [dnanexus/parliament2#41]
We have people who want to use the Parliament2 container on a local HPC infrastructure. Users aren't allowed to run docker, but can run containers using Singularity ( https://www.sylabs.io/singularity/ ). One of the main differences is that non-privileged users can run a container with Singularity. However, that seems to create permission problems with Parliament2. For example, this is the first several lines of output when we run the Parliament2 container with Singularity:

Set up and index BAM/CRAM
BAM file and index both exist in the mounted volume; continuing
ln: failed to create symbolic link '/home/dnanexus/input.bam': Permission denied
ln: failed to create symbolic link '/home/dnanexus/input.bam.bai': Permission denied
Generate contigs
[E::hts_open_format] Failed to open file input.bam
samtools view: failed to open "input.bam" for reading: No such file or directory

Then a bunch of errors because input.bam and input.bam.bai aren't found -- because the symlinks can't be created. I believe the symlink errors, above, emanate from lines 132 and 133 of parliament2.sh. Since the user running is non-privileged, the symlinks fail because they are being created in the /home/dnanexus path, which is owned by user dnanexus.

It would be very useful to be able to run the Parliament2 container with Singularity. I suspect this is a fairly common situation.

**Comment by slzarate** [comment]
Hi,

Thanks for reporting this use case. We currently do not have any plans to add compatibility with Singularity, but if you point me towards some documentation, I can take a look.

Thanks,
Samantha

**Comment by sameerd** [comment]
Hi, 

I too would like the ability to run Parliament2 via Singularity on an HPC system. The documentation for Singularity is at this link. [https://www.sylabs.io/guides/3.0/user-guide/](https://www.sylabs.io/guides/3.0/user-guide/)

A basic difference is that Singularity runs the container as the user on the HPC system. This means that the user does not have permission to write to /home/dnanexus. They do have permissions to read everything from /home/dnanexus. The only directories a user can write to are 

1. `/home/dnanexus/in`
2. `/home/dnanexus/out`
3. A working directory (which we don’t know the location of beforehand and is sometimes the user’s home directory)

Maybe the simplest solution would be to make writeable any directories the user needs to write to (like `/home/dnanexus` )? 

Incase you decide not to go that route, it might be possible to fix the paths in some of the scripts to use hardcoded paths? I put in a few minor changes to `parliament2.sh` and `runManta` [here](
https://github.com/dnanexus/parliament2/compare/master...sameerd:singularity_edits)
This allows singularity to run some programs like lumpy, delly, manta, breakseq, breakdancer and cnvnator and save their results. Running svtyper, survivor and svviz would require more changes that might not be so simple.

Thank you very much to @slzarate and any other authors for building this container and also for releasing it in an open source manner. It is much appreciated!

Rgds

**Comment by sameerd** [comment]
Hi, I made a few more edits to parliament2 and am now able to run the entire container with singularity. The fork with the singularity changes is [here](https://github.com/sameerd/parliament2)  and the singularity container is [here](https://www.singularity-hub.org/collections/2124). Hopefully this will help anyone who works on this issue in the future. 

Ideally I would have liked to have submitted a pull request with the changes but I don't have access to a server with docker to test the effects on the original code. 

Thanks once again to the original authors for providing this container. 

Rgds

**Comment by slzarate** [comment]
@sameerd Thank you so much! Could you make a pull request? I've implemented CI testing, so it should be able to automatically test effects on the original code.

**Comment by eburgueno** [comment]
@sameerd Thank you for this! just what I came to request myself.

I would strongly encourage the authors to ditch Docker and strongly look at Singularity for this type of containers. This is now the only way we support containers in our HPC.

Further to seamlessly dealing with mount points and user identities, singularity images seem to end up being smaller and can be distributed alongside input data as just another file; which guarantees reproducibility.

**Comment by jpdna** [comment]
@sameerd - could you provide an example of the `singularity run` command line including the Bindings parameter that you used successfully?  I am getting errors both from your Singularity container and the current parliament2 Master after the PR was merged - but I wonder if my run command is lacking.  Example errors I am getting from the run include samtools being unable to write:
```
samtools view: writing to standard output failed: Broken pipe
samtools view: error closing standard output: -1
```
Thanks!

**Comment by sameerd** [comment]
@jpdna The run command is at the bottom of the first comment of the PR #46. Search for 
`LANG= singularity run`

**Comment by eburgueno** [comment]
@jpdna check the FAQ: https://github.com/dnanexus/parliament2#samtools-error
