### ISSUE TITLE
Can this be built on a non docker environment.

### ISSUE THREAD

**Issue by RoydenClark** [dnanexus/parliament2#42]
Our current HPC environment does not have nor does it currently allow docker installations. Is there any way to build this from source without docker environment?

Thank you

**Comment by slzarate** [comment]
Hi,

Parliament2 requires a Docker environment, as we use Docker to manage the dependencies required (of which there are many). We do not currently have any plans to migrate away from using Docker.

However, Parliament2 has also been implemented on DNAnexus: https://www.dnanexus.com/. You can use DNAnexus to run Parliament2 without having to install Docker.

Samantha

**Comment by slzarate** [comment]
If you are interested in running Parliament2 on Singularity, see here for my response to this feature request: https://github.com/dnanexus/parliament2/issues/41
