### ISSUE TITLE
Only CNVNATOR and DELLY outputs 

### ISSUE THREAD

**Issue by CWYuan08** [dnanexus/parliament2#56]
Hi there, 

I have run Parliament2 with: 
docker run -v /Users/downloads/par2:/home/dnanexus/in -v /Users/downloads/par2/outputs:/home/dnanexus/out dnanexus/parliament2:0.1.9 --bam sorted.bam --bai sorted.bam.bai --fai c_elegans.fa.fai --r c_elegans.fa --breakdancer --breakseq --manta --cnvnator --lumpy --delly_deletion --delly_insertion --delly_inversion --delly_duplication --genotype --svviz --svviz_only_validated_candidates

however, I have only obtained results for CNVNATOR and DELLY; and it reported:
"No outputs of Manta found. Continuing. 
No Breakseq log files found.
No outputs of Breakseq found. Continuing.
Traceback (most recent call last):
  File "/BreakDancer2Merge.py", line 88, in <module>
    if int(data[h["Score"]]) <= 50:
IndexError: list index out of range
Reading calls ...
Can't parse sequence for chromosome I.
Can't parse sequence for chromosome II.
Can't parse sequence for chromosome III.
Can't parse sequence for chromosome IV.
Traceback (most recent call last):
  File "/convert_breakdancer_vcf.py", line 13, in <module>
    c2 = tab_split[3]
IndexError: list index out of range
Can't parse sequence for chromosome V.
Can't parse sequence for chromosome X.
Running SVTyper
Running SVTyper on Breakdancer outputs
grep: svtype_breakdancer: Is a directory
Running SVTyper on BreakSeq outputs
No BreakSeq VCF file found. Continuing.
Running SVTyper on CNVnator outputs
grep: svtype_cnvnator: Is a directory
Running SVTyper on Delly outputs
grep: svtype_delly_0: Is a directory
grep: svtype_delly_1: Is a directory
grep: svtype_delly_2: Is a directory
grep: svtype_delly_3: Is a directory
Running SVTyper on Lumpy outputs
grep: svtype_lumpy: Is a directory
Running SVTyper on Manta outputs
No Manta VCF file found. Continuing.
Preparing inputs for SURVIVOR
Adding sorted.breakdancer.svtyped.vcf to SURVIVOR inputs
Adding sorted.cnvnator.svtyped.vcf to SURVIVOR inputs
Adding sorted.delly.svtyped.vcf to SURVIVOR inputs
Adding sorted.lumpy.svtyped.vcf to SURVIVOR inputs
Running SURVIVOR
merging entries: 0
merging entries: 1618
merging entries: 12344
merging entries: 0
Running svviz "

How to fix this problem? 

Thank you very much
Best

**Comment by davidcotter** [comment]
Please check the  output of the failing tools from the log_files directory e.g. look at  manta_logs.tar.gz and see if there is any error there and post the error. I had a couple of issues with these tools: for Manta it was: 

 [ERROR] Received termination signal, shutting down running tasks...

and for breakdancer it didn't like by BAM file headers.

**Comment by CWYuan08** [comment]
@davidcotter Thank you for the tip, for manta it was:  Failed to complete master workflow, Unhandled Exception in TaskRunner-Thread-masterWorkflow
File "/miniconda/share/manta-1.4.0-1/lib/python/pyflow/pyflow.py", line 1069, in run
 (retval, retmsg) = self._run()
File "/miniconda/share/manta-1.4.0-1/lib/python/pyflow/pyflow.py", line 1121, in _run
self.workflow.workflow()
File "/miniconda/share/manta-1.4.0-1/lib/python/mantaWorkflow.py", line 883, in workflow
statsTasks = runStats(self,taskPrefix="getAlignmentStats")
File "/miniconda/share/manta-1.4.0-1/lib/python/mantaWorkflow.py", line 191, in runStats
dirTask=self.addTask(preJoin(taskPrefix,"makeTmpDir"), makeTmpStatsDirCmd, dependencies=dependencies, isForceLocal=True)
File "/miniconda/share/manta-1.4.0-1/lib/python/pyflow/pyflow.py", line 3689, in addTask
raise Exception("Task memory requirement exceeds full available resources")
Exception: Task memory requirement exceeds full available resources

For Breakseq it was: 
Traceback (most recent call last):
  File "./breakseq2-2.2/scripts/run_breakseq2.py", line 28, in <module>
    args.keep_temp, args.window, args.junction_length))
  File "/miniconda/lib/python2.7/site-packages/breakseq2/breakseq_top.py", line 96, in breakseq2_workflow
    breakseq_index.generate_bplib(bplib_gff, reference, bplib, junction_length)
  File "/miniconda/lib/python2.7/site-packages/breakseq2/breakseq_index.py", line 47, in generate_bplib
    flanks = sv.get_flanks()
  File "/miniconda/lib/python2.7/site-packages/breakseq2/biopy/io/SV.py", line 120, in get_flanks
    seqA=seqs.get_sequence(*seqs.get_window(self.name, self.start))
  File "/miniconda/lib/python2.7/site-packages/breakseq2/biopy/io/Fasta.py", line 20, in get_sequence
    seq = self.seqs[name].seq
KeyError: '1'

For Breakdancer, the logs are empty

For Lumpy, it was: samtools view: writing to standard output failed: Broken pipe
samtools view: error closing standard output: -1
mv: cannot stat 'lumpy.1.vcf.Yz2d1Oip7vVO/lumpy.1.vcf.sample1.lib1.discordants.bam': No such file or directory

**Comment by davidcotter** [comment]
>> Task memory requirement exceeds full available resources

How much  memory and how many cores does you machine have looks like it might not be enough.

**Comment by CWYuan08** [comment]
@davidcotter 
Memory: 32 GB 2400 MHz DDR4
hw.physicalcpu: 6
hw.logicalcpu: 12

**Comment by davidcotter** [comment]
Sorry not sure I would have thought 32 would be enough in your case unless there is not much of that 32 available.

**Comment by slzarate** [comment]
Hi @CWYuan08, thanks for contacting me. Sorry for the delayed response. @davidcotter brings up a good point. It does look as if you may be running out of resources. How many cores does your machine have, and how many GB/core? I am not sure how to interpret the stats you've posted.

Also, I notice you are running this on a c. elegans genome. Parliament2 is so far untested on non-human genomes, so there may be further debugging required. I would look into whether Breakdancer, Manta, and Lumpy work on non-human genomes (BreakSeq will for sure not work on non-hs37d5 genomes).

**Comment by AndrewCarroll** [comment]
I am going to go ahead and close this issue.
