### ISSUE TITLE
multiple bam files

### ISSUE THREAD

**Issue by yyx8671** [dnanexus/parliament2#57]
Hi, 

I want to have a test using parliament2. I have multiple bam files for one sample. When I use parliament2, can I put each bam file by specifying a '--bam' option or I need to merge all bam files into one? 

Thanks,
Andy

**Comment by slzarate** [comment]
Hi Andy,

Parliament2 is only meant to be run on one WGS BAM file at a time. You can merge the BAM files into one, or run Parliament2 multiple times and merge the final VCF outputs (we already do that in Parliament2 using [SURVIVOR](https://github.com/fritzsedlazeck/SURVIVOR/)).

**Comment by yyx8671** [comment]
Thanks so much @slzarate for your reply.
