### ISSUE TITLE
cannot execute the parliament2 at a remote server

### ISSUE THREAD

**Issue by mm538** [dnanexus/parliament2#58]
Hi, 

I encountered a problem when trying to run the parliament2 in a remote server (the administrator has add me into "sudo" privilege). 

**The problem detail is:**

1). docker has been installed (Docker version 1.13.1, build 07f3374/1.13.1)

2). the parliament2 is pulled by docker with info:
#####
Using default tag: latest
Trying to pull repository docker.io/dnanexus/parliament2 ...
latest: Pulling from docker.io/dnanexus/parliament2
Digest: sha256:2a1b0e5e9fff9598a48647c17659c74891ac2b56b460e802ce336db9a7656cc9
Status: Image is up to date for docker.io/dnanexus/parliament2:latest

3). when I run "parliament2" with provided command:  docker run parliament2 -h, an error shows:
 Unable to find image 'parliament2:latest' locally
Trying to pull repository docker.io/library/parliament2 ...
/usr/bin/docker-current: repository docker.io/parliament2 not found: does not exist or no pull access.
See '/usr/bin/docker-current run --help'.

############
Any suggestions here? Thank you a lot for your help in advance.

**Comment by slzarate** [comment]
Hi, a couple of things:

1. The latest image on DockerHub is not versioned, so it may be unstable. I recommend pulling `dnanexus/parliament2:0.1.9` for the latest stable version.
2. The run command is `docker run dnanexus/parliament2:<TAG>` if pulled from DockerHub.

**Comment by mm538** [comment]
Hi Samantha:

Thank you for your email.

By using your method, I can execute "parliament2.py" right now. Sweet.

Thank you again.

Best regards,

Hua Ke


________________________________
