### ISSUE TITLE
Parliament2 can also run for illumina mate-pairs reads instead paired end ?

### ISSUE THREAD

**Issue by unique379r** [dnanexus/parliament2#59]
Hi
I would like to run Illumina mate pair reads to obtain all types of SVs. Is it possible to use your tool ?
I used Delly and Lumpy to trick my reads and provided to BWA-MEM as reverse compliment sequence reads (R1 and R2) and further used callers to call the SVs. So I wonder, if is this also possible by PARLIAMENT2.

Thanks
Rupesh

**Comment by AndrewCarroll** [comment]
Hi Rupesh,

I am not sure, this is not something that we tested, but if you have tried and can report here, I am curious as to your results.
