### ISSUE TITLE
Parliament2 for 10xG data on non-human genome

### ISSUE THREAD

**Issue by MaestSi** [dnanexus/parliament2#62]
Dear Parliament2 developers,
should the software be able to deal with a 10x Genomics BAM file generated by Longranger pipeline?
Moreover, since I am not using a human reference genome, but I have a Grapevine genome assembled into 4700 contigs, should I exclude some of the tools?
Thanks in advance,
Simone

**Comment by AndrewCarroll** [comment]
Hi MaestSi,

This is a good question. I am not sure in advance which of the programs will work. I have not tested with a 10X file before. I would recommend you might want to run each method individually first and see what works.

Also, if you want to call on the smaller contigs, you will need to not run with the --filter_short_contigs flag.

**Comment by MaestSi** [comment]
Dear AndrewCarroll,
I tried running Parliament2 pipeline excluding only breakseq2, since of course I don't have a library for recurrent breakpoints in Grapevine, and it worked well!
Thank you,
Simone
