### ISSUE TITLE
cp: cannot stat '/home/dnanexus/in/None': No such file or directory

### ISSUE THREAD

**Issue by YTLogos** [dnanexus/parliament2#85]
Hi @Maciek416 
These days I have tried the parliament2 to call SVs. I get the following error:

```
cp: cannot stat '/home/dnanexus/in/None': No such file or directory
```

current working directory is named /home/dnanexus/ and looks like this:

```
.
├── input.bam
├── input.bai
├── ref_genome.fa.gz
└── outputs
```

Command used as follow:
```
docker run -v /home/dnanexus/:/home/dnanexus/in -v /home/dnanexus/outputs/:/home/dnanexus/out dnanexus/parliament2:latest --bam input.bam --bai input.bai -r ref_genome.fa.gz --breakdancer --cnvnator --manta --genotype

```

**Comment by ManavalanG** [comment]
This was [reported before](https://github.com/dnanexus/parliament2/issues/20) but no solution yet.

**Comment by husamia** [comment]
I am having this same problem with docker 

cp: cannot stat '/home/dnanexus/in/None': No such file or directory
mv: cannot stat '/home/dnanexus/in/None': No such file or directory
